jobs:
  - name: demo-env-variable-manifest-job
    type: manifest
    steps:
      - IN: demo-img
      - IN: demo-img-opts
      - TASK: managed
    flags:
      - demo-env-variable

  - name: demo-env-variable-deploy-job
    type: deploy
    steps:
      - IN: demo-env-variable-manifest-job
      - IN: demo-env-variable-ecs-cluster
      - TASK: managed
    flags:
      - demo-env-variable

  - name: demo-env-variable-runSh-job                                
    type: runSh                                 
    steps:                                      
      - IN: demo-env-variable-deploy-job                 
      - TASK:
        - script: echo "hello"
    flags:
      - demo-env-variable
