jobs:
  - name: demo-env-variable-manifest-job
    type: manifest
    steps:
      - IN: demo-env-variable-image
      - IN: demo-env-variable-image-opts
      - TASK: managed
    flags:
      - demo-env-variable

  - name: deploy-job
    type: deploy
    steps:
      - IN: demo-env-variable-manifest-job
      - IN: demo-env-variable-ecs-cluster
      - TASK: managed
    flags:
      - demo-env-variable

  - name: demo-env-variable-runSh-job                                
    type: runSh                                 
    steps:                                      
      - IN: deploy-job                 
      - TASK:
        - script: exit 0;
        - script: echo "testing env variable"
        - script: cat $DEPLOYJOB_STATE/manifests.json | jq '.'
        - script: cat $DEPLOYJOB_STATE/manifests.json | jq '.[].images' | jq '.[0].image'
        - script: cat $DEPLOYJOB_STATE/manifests.json | jq '.[].images' | jq '.[0].tag'
    flags:
      - demo-env-variable
