jobs:

  - name: release-single-component_runCI
    type: runCI
    steps:
      - OUT: demo-img

  - name: demo-man
    type: manifest
    steps:
      - IN: demo-img
      - IN: demo-img-opts
      - TASK: managed
    flags:
      - release-single-component

  - name: deploy-test-ecs
    type: deploy
    steps:
      - IN: demo-man
      - IN: env-aws-ecs-cluster
      - TASK: managed
    flags:
      - release-single-component

  - name: runSh-job                                
    type: runSh                                 
    steps:                                      
      - IN: deploy-test-ecs                 
      - TASK:
        - script: echo "hello"
        
